import { randomUUID } from "node:crypto";
import type { OperationStore } from "./operation-store.js";

export type ConnectorErrorKind = "auth" | "rate_limit" | "cancelled" | "not_found" | "conflict" | "network" | "unknown";
export interface ConnectorAccount { account_id: string; provider: "feishu"; status: "connected" | "expired" | "revoked" | "missing"; expires_at?: string; scopes: string[]; }
export interface ExternalObject { object_id: string; version: string; title: string; content: string; status: "draft" | "submitted"; }
export interface Connector { readonly provider: "feishu"; authorize(scopes: string[]): Promise<ConnectorAccount>; refresh(accountId: string): Promise<ConnectorAccount>; revoke(accountId: string): Promise<void>; status(accountId?: string): Promise<ConnectorAccount>; search(query: string, signal?: AbortSignal): Promise<ExternalObject[]>; read(objectId: string, signal?: AbortSignal): Promise<ExternalObject>; createDraft(input: { title: string; content: string; idempotencyKey: string }, signal?: AbortSignal): Promise<ExternalObject>; updateDraft(objectId: string, version: string, content: string, idempotencyKey: string, signal?: AbortSignal): Promise<ExternalObject>; submit(objectId: string, version: string, idempotencyKey: string, signal?: AbortSignal): Promise<ExternalObject>; }
export class ConnectorError extends Error { constructor(readonly kind: ConnectorErrorKind, message: string, readonly retryable = false) { super(message); } }
export function redactConnectorLog(value: unknown): string { return JSON.stringify(value, (_key, item) => typeof item === "string" && /(token|secret|authorization|cookie|password)/i.test(_key) ? "[REDACTED]" : item); }

/** Offline adapter: deterministic, no network or credentials, models Feishu draft semantics. */
export class FakeFeishuConnector implements Connector {
  readonly provider = "feishu" as const; private account: ConnectorAccount = { account_id: "fake-feishu", provider: "feishu", status: "missing", scopes: [] }; private objects = new Map<string, ExternalObject>(); private keys = new Map<string, ExternalObject>();
  async authorize(scopes: string[]) { this.account = { account_id: "fake-feishu", provider: "feishu", status: "connected", scopes: [...new Set(scopes)] }; return this.account; }
  async refresh(accountId: string) { if (accountId !== this.account.account_id) throw new ConnectorError("auth", "account not found"); if (this.account.status !== "connected") throw new ConnectorError("auth", "account is not connected"); return this.account; }
  async revoke(accountId: string) { if (accountId !== this.account.account_id) throw new ConnectorError("not_found", "account not found"); this.account = { ...this.account, status: "revoked" }; }
  async status(accountId?: string) { if (accountId && accountId !== this.account.account_id) throw new ConnectorError("not_found", "account not found"); return this.account; }
  private ensure() { if (this.account.status !== "connected") throw new ConnectorError("auth", "Feishu account is not connected"); }
  async search(query: string) { this.ensure(); return [...this.objects.values()].filter(o => o.title.includes(query) || o.content.includes(query)); }
  async read(objectId: string) { this.ensure(); const object = this.objects.get(objectId); if (!object) throw new ConnectorError("not_found", "external object not found"); return { ...object }; }
  async createDraft(input: { title: string; content: string; idempotencyKey: string }) { this.ensure(); const prior = this.keys.get(input.idempotencyKey); if (prior) return { ...prior }; const object: ExternalObject = { object_id: `feishu-draft-${randomUUID()}`, version: "1", title: input.title, content: input.content, status: "draft" }; this.objects.set(object.object_id, object); this.keys.set(input.idempotencyKey, object); return { ...object }; }
  async updateDraft(objectId: string, version: string, content: string, idempotencyKey: string) { this.ensure(); const prior = this.keys.get(idempotencyKey); if (prior) return { ...prior }; const object = this.objects.get(objectId); if (!object) throw new ConnectorError("not_found", "external object not found"); if (object.version !== version) throw new ConnectorError("conflict", "version conflict"); object.version = String(Number(object.version) + 1); object.content = content; this.keys.set(idempotencyKey, object); return { ...object }; }
  async submit(objectId: string, version: string, idempotencyKey: string) { this.ensure(); const prior = this.keys.get(idempotencyKey); if (prior) return { ...prior }; const object = this.objects.get(objectId); if (!object) throw new ConnectorError("not_found", "external object not found"); if (object.version !== version) throw new ConnectorError("conflict", "version conflict"); object.status = "submitted"; this.keys.set(idempotencyKey, object); return { ...object }; }
}

export async function createAndVerifyDraft(connector: Connector, operations: OperationStore, input: { taskId: string; sessionId?: string; runId?: string; title: string; content: string; scopes: string[] }): Promise<ExternalObject> {
  const account = await connector.status(); if (account.status !== "connected" || !input.scopes.every(scope => account.scopes.includes(scope))) throw new ConnectorError("auth", "required authorization scope is missing");
  const operationId = randomUUID(); const idempotencyKey = operationId; await operations.begin({ operation_id: operationId, task_id: input.taskId, run_id: input.runId, session_id: input.sessionId, step: 1, attempt: 1, sequence: 1, params_summary: `create draft: ${input.title}`.slice(0, 500), permission_state: "authorized", external_object_id: undefined });
  try { const draft = await connector.createDraft({ title: input.title, content: input.content, idempotencyKey }); const verified = await connector.read(draft.object_id); if (verified.version !== draft.version || verified.content !== draft.content || verified.status !== "draft") throw new ConnectorError("conflict", "draft read-back verification failed"); await operations.finish(operationId, "succeeded", "draft created and verified", draft.object_id); return verified; } catch (error) { await operations.finish(operationId, "failed", error instanceof Error ? error.message : String(error)); throw error; }
}
