import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
export type ScheduleStatus = "active" | "paused" | "failed" | "waiting_authorization";
export type MissedRunPolicy = "run_once" | "skip";
export type ScheduledTask = { id: string; name: string; prompt: string; timezone: string; day_of_week: number; hour: number; minute: number; status: ScheduleStatus; missed_run_policy: MissedRunPolicy; workspace_id?: string; parent_task_id?: string; budget?: number; next_run_at: string; last_trigger_key?: string; lease?: { owner: string; expires_at: string }; last_result?: "completed" | "failed" | "cancelled" | "needs_attention"; updated_at: string };
export type SchedulerHooks = { execute: (task: ScheduledTask, signal: AbortSignal) => Promise<"completed" | "failed" | "cancelled" | "needs_attention">; notify: (task: ScheduledTask, result: string, key: string) => Promise<void> };
export type Clock = () => Date;
export class SchedulerStore { constructor(private readonly filePath: string) {} private async load(): Promise<ScheduledTask[]> { try { return JSON.parse(await readFile(this.filePath, "utf8")) as ScheduledTask[]; } catch { return []; } } private async save(items: ScheduledTask[]) { await mkdir(path.dirname(this.filePath), { recursive: true }); const tmp = `${this.filePath}.${process.pid}.tmp`; await writeFile(tmp, JSON.stringify(items, null, 2)); await rename(tmp, this.filePath); } async list() { return this.load(); } async get(id: string) { const item = (await this.load()).find(t => t.id === id); if (!item) throw new Error("scheduled task not found"); return item; } async upsert(task: ScheduledTask) { const items = await this.load(); const next = items.some(t => t.id === task.id) ? items.map(t => t.id === task.id ? task : t) : [...items, task]; await this.save(next); return task; } async delete(id: string) { await this.save((await this.load()).filter(t => t.id !== id)); } }
export class LocalScheduler { private timer: ReturnType<typeof setInterval> | undefined; private readonly owner = randomUUID(); private readonly running = new Set<string>(); constructor(private readonly store: SchedulerStore, private readonly hooks: SchedulerHooks, private readonly clock: Clock = () => new Date(), private readonly tickMs = 30_000) {}
  async start() { await this.recoverLeases(); this.timer = setInterval(() => void this.tick(), this.tickMs); this.timer.unref?.(); await this.tick(); }
  stop() { if (this.timer) clearInterval(this.timer); this.timer = undefined; }
  async tick() { const now = this.clock(); for (const task of await this.store.list()) { if (task.status !== "active" || new Date(task.next_run_at) > now) continue; if (task.lease && new Date(task.lease.expires_at) > now) continue; if (this.running.has(task.id)) continue; const key = `${task.id}:${task.next_run_at}`; if (task.last_trigger_key === key) { await this.store.upsert({ ...task, next_run_at: nextWeekly(task, now).toISOString(), updated_at: now.toISOString() }); continue; } const leased = { ...task, lease: { owner: this.owner, expires_at: new Date(now.getTime() + Math.max(60_000, (task.budget ?? 60) * 1000)).toISOString() }, last_trigger_key: key, updated_at: now.toISOString() }; await this.store.upsert(leased); this.running.add(task.id); void this.execute(leased, key); } }
  private async execute(task: ScheduledTask, key: string) { const controller = new AbortController(); let result: ScheduledTask["last_result"] = "failed"; try { result = await this.hooks.execute(task, controller.signal); } catch { result = "failed"; } const now = this.clock(); const next = { ...task, status: result === "needs_attention" ? "waiting_authorization" : task.status, last_result: result, next_run_at: nextWeekly(task, now).toISOString(), lease: undefined, updated_at: now.toISOString() }; await this.store.upsert(next); this.running.delete(task.id); if (result === "completed" || result === "failed" || result === "needs_attention") await this.hooks.notify(next, result, `${key}:${result}`); }
  private async recoverLeases() { const now = this.clock(); for (const task of await this.store.list()) if (task.lease && new Date(task.lease.expires_at) <= now) await this.store.upsert({ ...task, lease: undefined, next_run_at: task.missed_run_policy === "run_once" ? now.toISOString() : nextWeekly(task, now).toISOString(), updated_at: now.toISOString() }); }
}
export function nextWeekly(task: Pick<ScheduledTask, "day_of_week" | "hour" | "minute">, from: Date): Date { const next = new Date(from); next.setUTCSeconds(0, 0); const delta = (task.day_of_week - next.getUTCDay() + 7) % 7; next.setUTCDate(next.getUTCDate() + delta); next.setUTCHours(task.hour, task.minute, 0, 0); if (next <= from) next.setUTCDate(next.getUTCDate() + 7); return next; }
