import { createApp } from "vue";
import { getCurrentWindow } from "@tauri-apps/api/window";
import App from "./App.vue";
import TrayMenu from "./tray/TrayMenu.vue";
import "./lilia.css";
import "./kimi.css";
import "./chat.css";
import "./skill-center.css";
import "./timeline.css";
import "./pipeline.css";
import "./link-menu.css";
import "./workbench.css";
import "./file-rail.css";
import "./typography.css";
import "./appearance.css";
import "./queue-dock.css";
import "./source-control.css";
import "./motion.css";
import { initializeAppearance } from "./services/appearance";

initializeAppearance();
const label = "__TAURI_INTERNALS__" in window ? getCurrentWindow().label : "main";
createApp(label === "tray-menu" ? TrayMenu : App).mount("#app");
