#!/usr/bin/env node
import "./env.js";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline/promises";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { IpcClient } from "./client.js";
import type { RuntimeEvent } from "@sztucode/protocol";

const args = process.argv.slice(2); const command = args[0] ?? "help";
const dataRoot = process.env.SZTU_DATA_DIR ?? path.join(os.homedir(), ".sztu");
const pidFile = path.join(dataRoot, "sztucode-ts.pid"); const traceFile = path.join(dataRoot, "traces", "runtime-ts-events.jsonl");
const startupAttempts = (): number => {
  const configured = Number(process.env.SZTU_STARTUP_TIMEOUT_MS ?? 15_000);
  const timeoutMs = Number.isFinite(configured) ? Math.min(60_000, Math.max(1_000, configured)) : 15_000;
  return Math.ceil(timeoutMs / 100);
};
function renderEvent(event: RuntimeEvent): void { if (event.type === "run.started") console.log(`[run] ${event.run_id}`); else if (event.type === "step.started") console.log(`[step ${event.step}] planning...`); else if (event.type === "llm.token") process.stdout.write(event.token); else if (event.type === "tool.call_started") console.log(`\n[tool] ${event.tool_name} ${JSON.stringify(event.params)}`); else if (event.type === "tool.call_finished") console.log(`[tool] ${event.tool_name} done ${event.elapsed_ms}ms`); else if (event.type === "tool.call_failed") console.error(`[tool] ${event.tool_name} failed: ${event.error_message}`); else if (event.type === "permission.requested") console.log(`\n[permission] ${event.tool_name}: ${event.param_preview}`); else if (event.type === "run.finished") console.log(`\n[run] ${event.status} ${event.steps} steps ${event.elapsed_s.toFixed(1)}s`); }
async function connect(handler: (event: RuntimeEvent) => void = renderEvent, attempts = 20): Promise<IpcClient> { const value = new IpcClient(undefined, undefined, handler); await value.connect(attempts); await value.request("event.subscribe", { topics: ["*"], scope: "global" }); return value; }
async function ping(attempts = 20): Promise<Record<string, unknown>> { const ipc = await connect(() => undefined, attempts); try { return await ipc.request("core.ping", { client: "sztucode-ts/0.2.0" }); } finally { ipc.close(); } }
async function startDaemon(): Promise<void> { const current = path.dirname(fileURLToPath(import.meta.url)); const bundled = path.resolve(current, "../runtime/main.js"); const workspace = path.resolve(current, "../../runtime-ts/dist/main.js"); const runtime = existsSync(bundled) ? bundled : workspace; if (!existsSync(runtime)) throw new Error("TypeScript runtime bundle is missing; run npm run build first"); const child = spawn(process.execPath, [runtime], { detached: true, stdio: "ignore", windowsHide: true, env: { ...process.env, SZTU_TS_HOST: process.env.SZTU_TS_HOST ?? process.env.SZTU_HOST ?? "127.0.0.1", SZTU_TS_PORT: process.env.SZTU_TS_PORT ?? process.env.SZTU_PORT ?? "7438" } }); child.unref(); await mkdir(dataRoot, { recursive: true }); await writeFile(pidFile, `${child.pid ?? ""}\n`, "utf8"); console.log(`started TypeScript daemon (pid ${child.pid ?? "unknown"})`); }
async function ensureDaemon(): Promise<void> { try { await ping(1); return; } catch { await startDaemon(); } try { await ping(startupAttempts()); } catch (error) { throw new Error(`TypeScript daemon did not become ready: ${error instanceof Error ? error.message : String(error)}`); } }
async function run(goal: string): Promise<number> { if (!goal.trim()) throw new Error("Usage: sztu-ts run --goal <task>"); let target = ""; let resolveDone: ((event: RuntimeEvent) => void) | undefined; const done = new Promise<RuntimeEvent>((resolve) => { resolveDone = resolve; }); const ipc = await connect((event) => { renderEvent(event); if (event.type === "run.finished" && (!target || event.run_id === target)) resolveDone?.(event); }); try { const result = await ipc.request("agent.run", { goal }); target = String(result.run_id); const event = await done; return event.type === "run.finished" && event.status === "success" ? 0 : 1; } finally { ipc.close(); } }
async function chat(projectArg?: string): Promise<number> { const ipc = await connect(); const project = projectArg && !projectArg.startsWith("-") ? path.resolve(projectArg) : process.cwd(); const opened = await ipc.request("workspace.open", { path: project }); const workspaceId = String((opened.workspace as { workspace_id?: unknown } | undefined)?.workspace_id ?? ""); const created = await ipc.request("session.create", { mode: "chat", workspace_id: workspaceId }); const sessionId = String(created.session_id); console.log(`[workspace: ${project}]\n[session: ${sessionId}]`); const readline = createInterface({ input: process.stdin, output: process.stdout }); try { while (true) { const input = (await readline.question("> ")).trim(); if (!input || input === "/exit") break; if (input === "/status") { console.log(JSON.stringify(await ipc.request("session.get", { session_id: sessionId }), null, 2)); continue; } if (input === "/compact") { console.log(JSON.stringify(await ipc.request("session.compact", { session_id: sessionId }), null, 2)); continue; } await ipc.request("session.send_message", { session_id: sessionId, content: input, client_message_id: `${Date.now()}-${Math.random().toString(16).slice(2)}` }); } } finally { readline.close(); await ipc.request("session.close", { session_id: sessionId }).catch(() => undefined); ipc.close(); } return 0; }
async function trace(runId?: string): Promise<number> { const raw = args.includes("--raw"); let offset = 0; const processChunk = (chunk: string) => { for (const line of chunk.split(/\r?\n/).filter(Boolean)) { try { const event = JSON.parse(line) as RuntimeEvent; if (runId && (event as { run_id?: string }).run_id !== runId) continue; console.log(raw ? line : `${(event as { ts?: string }).ts ?? ""}  ${(event as { type?: string }).type ?? ""}  ${JSON.stringify(event)}`); } catch { /* ignore corrupt rows */ } } }; try { const data = await readFile(traceFile, "utf8"); offset = Buffer.byteLength(data); processChunk(data); } catch { console.error(`trace file not found: ${traceFile}`); return 1; } if (!args.includes("--follow") && !args.includes("-f")) return 0; while (true) { try { const data = await readFile(traceFile, "utf8"); processChunk(data.slice(offset)); offset = Buffer.byteLength(data); } catch {} await new Promise((resolve) => setTimeout(resolve, 100)); } }
async function main(): Promise<number> { if (process.env.SZTU_AUTO_START === "1" && ["ping", "run", "chat"].includes(command)) await ensureDaemon(); if (command === "ping") { console.log(JSON.stringify(await ping(), null, 2)); return 0; } if (command === "run") return run(args[1] === "--goal" ? args.slice(2).join(" ") : args.slice(1).join(" ")); if (command === "chat") return chat(args[1]); if (command === "trace") return trace(args[1] && !args[1].startsWith("-") ? args[1] : undefined); if (command === "core" && args[1] === "start") { try { await ping(1); console.log("TypeScript daemon already running"); } catch { await startDaemon(); await ping(startupAttempts()); } return 0; } if (command === "core" && args[1] === "status") { try { const result = await ping(1); console.log(`running  ${result.server_version ?? ""}`); return 0; } catch { console.log("not running"); return 1; } } if (command === "core" && args[1] === "stop") { try { const ipc = await connect(() => undefined, 1); await ipc.request("core.shutdown", {}); ipc.close(); await unlink(pidFile).catch(() => undefined); console.log("stopped TypeScript daemon"); return 0; } catch { console.log("not running"); return 1; } } if (command === "--version" || command === "version") { console.log("0.2.0"); return 0; } console.log("Usage: sztu-ts <ping|run --goal <task>|chat [project]|trace [run_id]|core start|core status|core stop>"); return 1; }
main().then((code) => { process.exitCode = code; }).catch((error) => { console.error(`error: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; });
