<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { ArrowUp, Check, ChevronDown, FileText, Folder, Image, Music2, Network, Plus, Presentation, RefreshCw, Search, Sparkles, Table2, Video, WandSparkles, X } from "@lucide/vue";
export type ChatView = "home" | "plugins" | "automations" | "ppt" | "cluster" | "research" | "document" | "website" | "sheet" | "project";
const props = defineProps<{ view: ChatView; connected: boolean }>();
const emit = defineEmits<{ submit: [content: string]; navigate: [view: ChatView]; openProject: [] }>();
const prompt = ref(""); const pptCategory = ref("全部"); const pluginCategory = ref("全部插件"); const selectedTemplate = ref(0); const projectName = ref(""); const projectCreated = ref(false); const automationFormOpen = ref(false); const automationName = ref(""); const pluginQuery = ref(""); const pluginTab = ref<"插件" | "技能">("插件"); const installed = ref(new Set(["图像生成", "音频生成"]));
const viewConfig = computed(() => ({ ppt: ["输入你想创作的 PPT 主题","PPT","选择模板"], cluster: ["给 AI 团队派个活...","集群","集群精选案例"], research: ["描述你的问题，生成深度研究报告","深度研究","深度研究精彩案例"], document: ["上传文档进行编辑，或从零开始创建","文档","文档精选案例"], website: ["描述你的网站想法，风格、功能、数据库都可以","网站","选择模板"], sheet: ["上传表格进行分析，或从零开始创建","表格","表格精选案例"] }[props.view as "ppt" | "cluster" | "research" | "document" | "website" | "sheet"]));
const rawTemplates: Record<string, [string,string,string][]> = {
 ppt: [["自由风格","留白与柔和渐变","mist"],["静青尽调","并购尽职调查报告","blueprint"],["粉彩推导","连续时间生成建模","sky"],["季度复盘","关键指标与增长洞察","night"],["一网通办","服务运行复盘报告","paper"],["年度经营","2026 经营报告","cream"]],
 cluster: [["黑洞：GARGANTUA","交互式宇宙实验","space"],["3D 复古打字机","产品创意与实时渲染","typewriter"],["Bloomberg 风格看板","全球股市数据终端","terminal"]],
 research: [["推理芯片：四十二年周期","产业与技术路线研究","research-a"],["交互式论文：Attention Residuals","论文解读与可视化","research-b"],["船运：不是一个周期","行业数据深度拆解","research-c"]],
 document: [["比亚迪投资简报","市场表现与财务分析","doc-a"],["SCI 科研论文写作","标准学术论文结构","doc-b"],["中国石油业绩简报","经营数据可视化","doc-c"]],
 website: [["赛博雨幕","记忆实验室","web-a"],["艺术藏馆","伍尔芙的房间","web-b"],["光影空间","沉浸式建筑展览","web-c"],["静谧旅店","精品酒店主页","web-d"],["行星地平线","未来主题展示站","web-e"],["视觉档案","网格式艺术作品集","web-f"]],
 sheet: [["个人健康年度复盘","健康趋势与运动分析","sheet-a"],["脑科学分析表","实验数据与分布研究","sheet-b"],["Hermès 20 年经营全景表","长期财务表现","sheet-c"]]
};
const templates = computed(() => (rawTemplates[props.view] ?? []).map(([title, subtitle, tone]) => ({ title, subtitle, tone })));
const plugins = [["灵动报告","把静态报告变成灵动、鲜活的网页","效率办公","report"],["金融投资分析","二级市场研究与投资组合工作流","金融","finance"],["投资银行私募股权","投行与私募股权一级市场工作流","金融","bank"],["企业财务会计","企业财务与会计工作流插件","金融","accounting"],["灵感池","给创意工作者的设计灵感库","创意设计","idea"],["国家及行业标准查询","查询国家标准与行业标准","效率办公","standard"],["视频生成","根据文字描述生成高质量视频","创意设计","video"],["图像生成","根据文字描述生成高质量图像","创意设计","image"],["音频生成","根据文字描述生成高质量音频","创意设计","audio"],["万得金融数据服务","专业全面的金融数据基础设施","金融","wind"],["国际组织官方数据","查询 WHO、FAO 等公开数据","效率办公","global"],["Stripe","连接账户并查看客户与余额","效率办公","stripe"]] as const;
const filteredPlugins = computed(() => plugins.filter(item => (pluginCategory.value === "全部插件" || item[2] === pluginCategory.value) && (!pluginQuery.value || (item[0] + item[1]).toLowerCase().includes(pluginQuery.value.toLowerCase()))));
function submit() { const value = prompt.value.trim(); if (!value) return; emit("submit", value); prompt.value = ""; }
// 回车直接发送；Ctrl/Shift/Alt + 回车保留默认换行行为，且忽略中文输入法候选确认
function onComposerKeydown(event: KeyboardEvent) { if (event.key !== "Enter" || event.isComposing) return; if (event.shiftKey || event.ctrlKey || event.metaKey || event.altKey) return; event.preventDefault(); submit(); }
function togglePlugin(name: string) { const next = new Set(installed.value); next.has(name) ? next.delete(name) : next.add(name); installed.value = next; }
function createProject() { if (projectName.value.trim()) projectCreated.value = true; }
watch(() => props.view, () => { selectedTemplate.value = 0; if (props.view !== "project") projectCreated.value = false; });
</script>
<template>
 <section v-if="view === 'plugins'" class="chat-plugins">
  <header class="plugin-top"><nav><button v-for="tab in ['插件','技能'] as const" :key="tab" :class="{active: pluginTab === tab}" @click="pluginTab = tab">{{ tab }}</button></nav><button class="plugin-close" aria-label="返回对话" @click="emit('navigate','home')"><X :size="19" /></button></header>
  <div v-if="pluginTab === '插件'" class="plugin-content"><div class="plugin-heading"><div><h1>插件</h1><p>将外部工具接入 Kimi，使它可以使用应用和服务完成任务</p></div><label><Search :size="15" /><input v-model="pluginQuery" placeholder="搜索插件" /></label></div><div class="plugin-categories"><button v-for="item in ['全部插件','金融','效率办公','代码开发','创意设计']" :key="item" :class="{active: pluginCategory === item}" @click="pluginCategory = item">{{ item }}</button></div><div class="plugin-grid"><button v-for="item in filteredPlugins" :key="item[0]" class="plugin-card" @click="togglePlugin(item[0])"><span class="plugin-logo" :class="'plugin-logo--' + item[3]"><Image v-if="item[3] === 'image'" :size="23" /><Video v-else-if="item[3] === 'video'" :size="23" /><Music2 v-else-if="item[3] === 'audio'" :size="23" /><Sparkles v-else :size="22" /></span><span><b>{{ item[0] }}</b><small>{{ item[1] }}</small></span><Check v-if="installed.has(item[0])" :size="16" /><Plus v-else class="plugin-add" :size="16" /></button></div></div>
  <div v-else class="skills-empty"><WandSparkles :size="46" /><h1>技能</h1><p>在对话中输入 <kbd>/</kbd> 快速调用已安装技能。</p><button @click="emit('navigate','home')">去对话中试试</button></div>
 </section>
 <section v-else-if="view === 'automations'" class="chat-automations"><header><div><h1>定时任务</h1><p>按计划自动处理重复工作，并把结果送达给你</p></div><button @click="automationFormOpen = !automationFormOpen"><Plus :size="16" />新建任务</button></header><form v-if="automationFormOpen" class="automation-form" @submit.prevent="automationFormOpen = false"><label>任务名称<input v-model="automationName" placeholder="例如：每周项目进展汇总" /></label><label>执行频率<select><option>每天 09:00</option><option>每周一 09:00</option><option>每月 1 日 09:00</option></select></label><button :disabled="!automationName.trim()">保存任务</button></form><div v-else class="automation-empty"><RefreshCw :size="42" /><h2>暂无定时任务</h2><p>创建后，Kimi 会按设定时间自动执行并保存结果。</p></div></section> <section v-else-if="view === 'project'" class="chat-project"><div v-if="!projectCreated" class="project-create-card"><h1>新建项目</h1><p>同一件事，都在这里聊</p><div class="project-folders"><span /><span /><button aria-label="选择本地文件夹" @click="emit('openProject')"><Folder :size="78" /><Plus :size="34" /></button><span /><span /></div><form @submit.prevent="createProject"><input v-model="projectName" autofocus placeholder="取个名字" /><button :disabled="!projectName.trim()">创建项目</button></form></div><div v-else class="project-success"><span><Check :size="30" /></span><h1>{{ projectName }} 已创建</h1><p>现在可以把相关对话、文档和资料都放进这个项目。</p><button @click="emit('navigate','home')">开始对话</button></div></section>
 <section v-else class="chat-workspace" :class="'chat-workspace--' + view"><button class="upgrade-pill"><Music2 :size="16" />升级套餐</button><div class="dot-wordmark" aria-label="Kimi"><span v-for="n in 72" :key="n" :class="{accent: [11,29,46,63].includes(n)}" /></div><form class="chat-composer" @submit.prevent="submit"><textarea v-model="prompt" :placeholder="viewConfig?.[0] || '输入 / 唤起插件和技能'" rows="3" @keydown="onComposerKeydown" /><div class="chat-toolbar"><button type="button" aria-label="添加附件"><Plus :size="20" /></button><button v-if="viewConfig" type="button" class="active-tool"><Presentation v-if="view === 'ppt'" :size="16" /><Network v-else-if="view === 'cluster'" :size="16" /><FileText v-else-if="view === 'document' || view === 'research'" :size="16" /><Table2 v-else-if="view === 'sheet'" :size="16" /><Image v-else :size="16" />{{ viewConfig[1] }}</button><span /><button type="button" class="model-button">K3 <small>进阶</small><ChevronDown :size="14" /></button><button class="chat-send" type="submit" :disabled="!prompt.trim() || !connected"><ArrowUp :size="20" /></button></div><button class="project-selector" type="button" @click="emit('navigate','project')"><Folder :size="16" />选择项目<ChevronDown :size="14" /></button></form>
  <div v-if="view === 'home'" class="quick-tools"><button v-for="item in [['ppt','PPT'],['cluster','集群'],['research','深度研究'],['document','文档'],['website','网站'],['sheet','表格']]" :key="item[0]" @click="emit('navigate', item[0] as ChatView)">{{ item[1] }}</button></div>
  <section v-else-if="viewConfig" class="template-section"><header><h2>{{ viewConfig[2] }}</h2><button v-if="view === 'sheet'" @click="selectedTemplate = (selectedTemplate + 1) % templates.length"><RefreshCw :size="15" />换一换</button></header><div v-if="view === 'ppt'" class="template-categories"><button v-for="item in ['全部','战略咨询','金融投资','工作汇报','宣传推广','学术研究']" :key="item" :class="{active: pptCategory === item}" @click="pptCategory = item">{{ item }}</button></div><div class="template-grid"><button v-for="(item,index) in templates" :key="item.title" :class="{selected: selectedTemplate === index}" @click="selectedTemplate = index"><span class="template-preview" :class="'template-preview--' + item.tone"><Check v-if="selectedTemplate === index" :size="18" /><b>{{ item.subtitle }}</b></span><strong>{{ item.title }}</strong></button></div></section><small v-if="view !== 'home'" class="ai-disclaimer">内容由 AI 生成，请仔细甄别</small>
 </section>
</template>
